server:
  port: 2108
  context-path: /
  
eureka:
  instance:
    preferIpAddress: true # Register the IP of the service rather than the server name
  client:
    registerWithEureka: true
    fetchRegistry: true # Pull down a local copy of registry, refresh after every 30s
    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
      defaultZone: https://jfood-eureka.herokuapp.com/eureka


#security.oauth2.resource.user-info-uri=http://localhost:2108/v1/account/info
#security.oauth2.resource.filter-order = 3
#
### Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
#spring.datasource.driver-class-name = com.mysql.jdbc.Driver
#spring.datasource.url = jdbc:mysql://localhost:3306/jfood_account?useSSL=false&characterEncoding=UTF-8
#spring.datasource.username = root
#spring.datasource.password = 1234
#
#
### Hibernate Properties
## The SQL dialect makes Hibernate generate better SQL for the chosen database
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect
#spring.jpa.properties.hibernate.show_sql = true
## Hibernate ddl auto (create, create-drop, validate, update)
#spring.jpa.hibernate.ddl-auto = update