server:
  port: 2308
  context-path: /
  
eureka:
  instance:
    preferIpAddress: true # Register the IP of the service rather than the server name
  client:
    registerWithEureka: true
    fetchRegistry: true # Pull down a local copy of registry, refresh after every 30s
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
